# Generated by Django 5.2 on 2025-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nivel de habilidad (1-100)')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='habilidades_iconos/')),
            ],
        ),
    ]
