# Generated by Django 5.2 on 2025-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
